apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}
data:
{{if .RootUser}}  rootUser: {{.RootUser}}{{end}}
{{if .RootHost}}  rootHost: {{.RootHost}}{{end}}
{{if .RootPassword}}  rootPassword: {{.RootPassword}}{{end}}
