apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  instances: 1
  secretName: mypwds
  tlsUseSelfSigned: true
  backupProfiles:
  - name: {{.BackupProfileName}}
    dumpInstance:
      storage:
        ociObjectStorage:
          prefix: {{.OciStoragePrefix}}
          bucketName: {{.BucketName}}
          credentials: {{.OciCredentialsBackup}}
