apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  instances: 2
  secretName: mypwds
  tlsUseSelfSigned: true
  backupProfiles:
  - name: {{.BackupProfileNameVolume}}
    dumpInstance:
      dumpOptions:
        excludeSchemas: ["excludeme"]
      storage:
        persistentVolumeClaim:
          claimName: {{.BackupVolumeName}}
  - name: {{.BackupProfileNameOci}}
    dumpInstance:
      storage:
        ociObjectStorage:
          prefix: {{.OciStoragePrefix}}
          bucketName: {{.BucketName}}
          credentials: {{.OciCredentials}}
  - name: snapshot
    snapshot:
      storage:
        persistentVolumeClaim:
          claimName: {{.BackupVolumeName}}
